/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_driver_Jni */

#ifndef _Included_cn_itcast_driver_Jni
#define _Included_cn_itcast_driver_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_driver_Jni
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_itcast_driver_Jni_Login
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
