
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_driver_Jni */

#include "User.h"
#include "JniUtil.h"

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_driver_Jni
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_itcast_driver_Jni_Login
  (JNIEnv *env, jobject, jstring username, jstring password)
{
    char* cUsername = JniUtil::JString2CStr(env, username);
    char* cPassword = JniUtil::JString2CStr(env, password);

    bool ret = Login(cUsername, cPassword);

    JniUtil::DeleteCStr(cUsername);
    JniUtil::DeleteCStr(cPassword);

    return ret;
}

/*
 * Class:     cn_itcast_driver_Jni
 * Method:    SetStatus
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_itcast_driver_Jni_SetStatus
  (JNIEnv *, jobject, jint status)
{
    return SetStatus(status);
}

/*
 * Class:     cn_itcast_driver_Jni
 * Method:    UpdateGeoInfo
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_cn_itcast_driver_Jni_UpdateGeoInfo
  (JNIEnv *, jobject, jdouble lng, jdouble lat)
{
    return UpdateGeoInfo(lng, lat);
}

#ifdef __cplusplus
}
#endif
